services:
  - type: web
    name: wado-cdn
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    disk:
      name: wado-files
      mountPath: /app/files
      sizeGB: 1
    envVars:
      - key: PORT
        value: 8080
